<<<<<<< HEAD
# Generated by Django 4.2.6 on 2023-10-26 13:36
=======
# Generated by Django 4.2.5 on 2023-10-22 20:39
>>>>>>> f70a6a7f5382a5a39c22d5f759bbee8cada889d1

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
<<<<<<< HEAD
            name='student',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('student_name', models.CharField(max_length=50)),
                ('student_email', models.EmailField(max_length=254)),
                ('student_course', models.CharField(max_length=50)),
                ('student_progress', models.TextField()),
=======
            name='user',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=50)),
                ('password', models.CharField(max_length=128)),
>>>>>>> f70a6a7f5382a5a39c22d5f759bbee8cada889d1
            ],
        ),
    ]
