# Generated by Django 4.2.5 on 2023-10-14 21:45

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Time',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('day', models.CharField(max_length=50, unique=True)),
                ('opening_hours', models.CharField(max_length=100)),
            ],
        ),
    ]
