# Generated by Django 4.2.6 on 2023-11-14 15:09

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('Blog', '0002_blog'),
    ]

    operations = [
        migrations.AlterField(
            model_name='blog',
            name='des',
            field=models.CharField(max_length=500),
        ),
    ]
