# Generated by Django 4.2.6 on 2023-11-14 15:14

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('Blog', '0004_alter_blog_des'),
    ]

    operations = [
        migrations.AlterField(
            model_name='blog',
            name='des',
            field=models.TextField(max_length=100),
        ),
    ]
